import "./Effect/flatMap"
import "./Effect/instruction"
import "./Effect/map"
import "./Effect/succeed"
import "./Effect/type"
import "./Effect/do"
import "./Effect/delay"
import "./Effect/bind"
import "./Effect/pipe"
import "./Effect/forever"
import "./Effect/zipLeft"
import "./Effect/zipRight"

export { $Effect } from "./Effect/type"
