import "./Effect/flatMap.js"
import "./Effect/instruction.js"
import "./Effect/map.js"
import "./Effect/succeed.js"
import "./Effect/type.js"
import "./Effect/do.js"
import "./Effect/delay.js"
import "./Effect/bind.js"
import "./Effect/pipe.js"
import "./Effect/forever.js"
import "./Effect/zipLeft.js"
import "./Effect/zipRight.js"
import "./Effect/die.js"
import "./Effect/tuple.js"

export { $Effect } from "./Effect/type.js"
