import "./Option/emptyOf"
import "./Option/flatMap"
import "./Option/fold"
import "./Option/getOrElse"
import "./Option/none"
import "./Option/pipe"
import "./Option/some"
import "./Option/get"
import "./Option/isSome"
import "./Option/isNone"

export { $Option } from "./Option/type"
