import "./Option/emptyOf.js"
import "./Option/flatMap.js"
import "./Option/fold.js"
import "./Option/getOrElse.js"
import "./Option/none.js"
import "./Option/pipe.js"
import "./Option/some.js"
import "./Option/get.js"
import "./Option/isSome.js"
import "./Option/isNone.js"
import "./Option/equals.js"

export { $Option } from "./Option/type.js"
